### PR TITLE
Also set CUDA host compiler.

### PR DESCRIPTION
**Pull request by bowie7070**
Allows nvcc to find cl.exe without it being in the PATH.

### CODE REVIEW

**Comment by MarkSchofield** [comment]
Thanks for the PR, @bowie7070. TBH, I'm not familiar with `CMAKE_CUDA_HOST_COMPILER` - I'll take a look and ramp-up a little. Do you have details on the use-case here?

**Comment by MarkSchofield** [comment]
[The documentation for `CMAKE_<LANG>_HOST_COMPILER`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_HOST_COMPILER.html#variable:CMAKE_%3CLANG%3E_HOST_COMPILER) seems to be a good starting point. It says:

> The CMAKE_<LANG>_HOST_COMPILER variable may be set explicitly before CUDA or HIP is first enabled by a [project()](https://cmake.org/cmake/help/latest/command/project.html#command:project) or [enable_language()](https://cmake.org/cmake/help/latest/command/enable_language.html#command:enable_language) command. This can be done via -DCMAKE_<LANG>_HOST_COMPILER=... on the command line or in a [toolchain file](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-toolchain). Or, one may set the [CUDAHOSTCXX](https://cmake.org/cmake/help/latest/envvar/CUDAHOSTCXX.html#envvar:CUDAHOSTCXX) or [HIPHOSTCXX](https://cmake.org/cmake/help/latest/envvar/HIPHOSTCXX.html#envvar:HIPHOSTCXX) environment variable to provide a default value.

So setting `CMAKE_CUDA_HOST_COMPILER` in a toolchain seems like a reasonable thing to do, but it goes on to say:

> Note Since CMAKE_<LANG>_HOST_COMPILER is meaningful only when the [CMAKE_<LANG>_COMPILER_ID](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html#variable:CMAKE_%3CLANG%3E_COMPILER_ID) is NVIDIA, it does not make sense to set CMAKE_<LANG>_HOST_COMPILER without also setting CMAKE_<LANG>_COMPILER to NVCC.

And setting `CMAKE_<LANG>_COMPILER` to NVCC doesn't seem reasonable for _this_ toolchain (i.e.  <https://github.com/MarkSchofield/WindowsToolchain>) to do, I'd have to teach it all about NVCC. Having a separate NVCC toolchain, and if _that_ toolchain wants to 'wrap'/'consume' _this_ toolchain, then that sounds like better encapsulation..?

If you have details on how you're consuming NVCC, I'd love to learn more.

**Comment by bowie7070** [comment]
Thanks for taking a look at my PR. 

> And setting CMAKE_<LANG>_COMPILER to NVCC doesn't seem reasonable for this toolchain (i.e. https://github.com/MarkSchofield/WindowsToolchain) to do,

Agreed, setting CMAKE_CUDA_COMPILER in this toolchain would be problematic.

> I'd have to teach it all about NVCC. Having a separate NVCC toolchain, and if that toolchain wants to 'wrap'/'consume' this toolchain, then that sounds like better encapsulation..?

The challenge is that there are sometimes multiple versions of NVCC installed and possibly in custom locations so providing a general way to find the right NVCC is tricky. The way I like to encapsulate the Cuda compiler is that I have is a CMakePresets.json file which controls the version of NVCC and then uses this toolchain file as a chainload file with vcpkg. The problem that I then have is that the host compiler is not found because for some reason it doesn't default to being the same as the C++ compiler.

```
{
    "version": 3,
    "configurePresets": [
        {
            "name": "our-defaults",
            "hidden": true,
            "binaryDir": "c:/b/${sourceDirName}-${presetName}",
            "cacheVariables": {
                "CMAKE_TOOLCHAIN_FILE": "${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake",
                "VCPKG_OVERLAY_TRIPLETS": "${sourceDir}/triplets",
                "VCPKG_INSTALL_OPTIONS": "--x-buildtrees-root=c:/b/vbt"
            },
            "environment": {
                "VCPKG_BINARY_SOURCES": "clear;files,c:/b/vcpkg-binarysource,readwrite"
            }
        },
        {
            "name": "x-x64",
            "hidden": true,
            "inherits": [ "our-defaults" ],
            "environment": {
                "VCPKG_DOWNLOADS": "$env{USERPROFILE}/vcpkg-downloads"
            },
            "cacheVariables": {
                "VCPKG_CHAINLOAD_TOOLCHAIN_FILE":"${sourceDir}/WindowsToolchain/Windows.MSVC.toolchain.cmake",
                "VCPKG_TARGET_TRIPLET": "x64-windows-mixed",
                "CMAKE_INTERPROCEDURAL_OPTIMIZATION": "ON",
                "CMAKE_CUDA_COMPILER": "C:/cuda/v12.5/bin/nvcc.exe",
                "CUDA_TOOLKIT_ROOT_DIR": "C:/cuda/v12.5"
            }
        },
        { "name": "ninja-x64", "inherits": "x-x64", "generator": "Ninja Multi-Config"
        }
    ],
```

**Comment by MarkSchofield** [comment]
OK, so you're setting `CMAKE_CUDA_COMPILER`. And `CMAKE_CUDA_COMPILER` is also used by [FindCUDAToolkit](https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#findcudatoolkit). So perhaps `CMAKE_CUDA_COMPILER` is a reasonable way to detect if the invocation wants CUDA support, so setting `CMAKE_CUDA_HOST_COMPILER` would be OK in that scenario...?

So, how about the change being (something like):

```cmake
if(CMAKE_CUDA_COMPILER)
    if((NOT CMAKE_CUDA_HOST_COMPILER) AND (NOT $ENV{CUDAHOSTCXX}))
        set(CMAKE_CUDA_HOST_COMPILER "${CMAKE_CXX_COMPILER}")
    endif()
endif()
```

That way:
1. We're checking `CMAKE_CUDA_COMPILER`, so that `CMAKE_CUDA_HOST_COMPILER` isn't set when it's not a CUDA invocation
2. If `CMAKE_CUDA_HOST_COMPILER` is already set, we're not stomping it.
3. If the `CUDAHOSTCXX` environment variable is set, we're not setting `CMAKE_CUDA_HOST_COMPILER` so that CMake's `FindCUDA`/`FindCUDAToolkit`/`enable_language(CUDA)` support will pick up the `CUDAHOSTCXX` environment variable.

That seems like reasonable due diligence? What do you think?

**Comment by bowie7070** [comment]
I think since you're aiming to be general those changes make sense. I would expect that the majority of the time the host compiler will not be known and these changes have no impact. However, in the case that a specific host compiler is required to match the cuda version selected these changes would be necessary.

Do you need me to revise the PR? Or do something else to progress this?

**Comment by MarkSchofield** [comment]
If you don't mind making the changes, that would be great - it'd get you some kudos for starting the conversation. If you'd rather not, let me know, and I'll have a go when I get a chance. Thanks!

**Comment by MarkSchofield** [comment]
Infact, I spent a little time looking at this and realized my code snippet wasn't right - `(NOT $ENV{CUDAHOSTCXX})` should be `(NOT DEFINED ENV{CUDAHOSTCXX})`. If you're OK with it, I'll pull together a fix based on my more 'defensive' change, and try and include a sample, too.

**Comment by bowie7070** [comment]
I can look at this detail in a couple of days. If you want to handle it or build more on it, that's great. I can confirm that whatever is done works in my case and I'll be happy. On the other hand I can make the changes in a few days if you're happy to wait.

**Comment by MarkSchofield** [comment]
I've been looking at this, and pushed my current 'draft' to [mschofie/cuda](https://github.com/MarkSchofield/WindowsToolchain/commits/mschofie/cuda/). I'll try things out a little more, and send a PR shortly.

**Comment by bowie7070** [comment]
Your changes look good. Plus it is great to see tests. I was hoping to have more time to assist with this but my week at work has been more full than I anticipated and it doesn't look like it is slowing down soon. I just want to see this behaviour incorporated so feel free to continue with your PR.

**Comment by MarkSchofield** [comment]
Thanks for your help, @bowie7070. I've completed #106.

**Pull request closed without merging**
