### PR TITLE
prevent any downloads on UNIX hosts

### PR DESCRIPTION
**Pull request by ClausKlein**
and use `find_program() `with **NAMES** parameters

### CODE REVIEW

**Comment by MarkSchofield** [comment]
I'm not sure I understand the use case here. Are you including the whole toolchain unconditionally? I'd anticipated that the toolchain would be specified on a Windows-specific preset (like the examples do), or on a command-line that's Windows-specific. Rather than short-circuiting the individual vswhere.cmake and nuget.cmake files to avoid downloads by default (which I do want to fix as per the feedback in #18), it's probably more self-describing to add a check to the toolchain files (i.e. `Windows.Clang.toolchain.cmake` and `Windows.MSVC.toolchain.cmake`) themselves, say,

```cmake
if(NOT (CMAKE_HOST_SYSTEM_NAME STREQUAL Windows))
    return()
endif()
```

immediately after the `include_guard`. Potentially with a `message` saying that it's a bit peculiar to be including a very host specific toolchain on the wrong host.

Whilst your fix stops the downloads, the toolchain files will have already been included and set a whole bunch of variables that are inappropriate. Unless I've misunderstood your use-case. Which is entirely possible.

**Comment by MarkSchofield** [comment]
I've created #45 and #46 showing how I'd rather address what I _think_ are your concerns. Thoughts?

**Comment by ClausKlein** [comment]
> I've created #45 and #46 showing how I'd rather address what I _think_ are your concerns. Thoughts?

Thanks, the background of MR is, that we have Problems on our company `CI` to download SW from Internet.
Our companies rules force no access to the Internet while building SW.

We are using `package_options` which is using your `WindowToolchain` project.

We were wondering why the toolchain was trying to download `ninja`, which was already installed with PIP and in path.

While analysing what the toolchain try to download and why, I tested this on `WSL` (Linux)

**Comment by ClausKlein** [comment]
I tried this to check why Ninja is not found:
```bash
bash-3.2$ cmake -B build -G Ninja -S . --preset windows-clang-x64 
Preset CMake variables:

  CLANG_TIDY_CHECKS="bugprone*,-bugprone-easily-swappable-parameters"
  CMAKE_SYSTEM_PROCESSOR="x64"
  CMAKE_SYSTEM_VERSION="10.0.19041.0"
  CMAKE_TOOLCHAIN_FILE="../Windows.Clang.toolchain.cmake"
  CMAKE_VS_VERSION_PRERELEASE="ON"
  CMAKE_VS_VERSION_RANGE="[16.0,18.0)"
  CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION_MAXIMUM="10.0.19041.0"
  CPPWINRT_PROJECTION_ROOT_PATH="/Users/clausklein/Workspace/cmake/WindowsToolchain/example/__cppwinrt"
  CPPWINRT_VERSION="2.0.220418.1"
  NUGET_PACKAGE_ROOT_PATH="/Users/clausklein/Workspace/cmake/WindowsToolchain/example/__packages"
  TOOLCHAIN_TOOLS_PATH="/Users/clausklein/Workspace/cmake/WindowsToolchain/example/__tools"

CMake Error at /Users/clausklein/Workspace/cmake/WindowsToolchain/Windows.Clang.toolchain.cmake:88 (find_program):
  Could not find CMAKE_C_COMPILER using the following names: clang.exe
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.24.2/share/cmake/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:6 (project)


CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
bash-3.2$

bash-3.2$ which ninja     
/usr/local/bin/ninja
bash-3.2$ ninja --version
1.11.1
bash-3.2$ 
```

**Comment by MarkSchofield** [comment]
I imagine Ninja is not found because my `find_program` is wrong - as you pointed out in #46. I filed #48 to track that.

I still don't understand your use-case - you're using the Toolchain from WSL? Are you expecting to run cmake from within WSL and have it find the Windows binaries in a 'cross-compilation'-like scenario. That's *potentially* something that could work, but #45 is probably a step backwards in that regard. If cross-compilation from WSL to produce Window binaries is a use-case you're looking for can you file an issue with the request? Thanks!

**Comment by ClausKlein** [comment]
> I still don't understand your use-case - you're using the Toolchain from WSL? Are you expecting to run cmake from within WSL and have it find the Windows binaries in a 'cross-compilation'-like scenario. That's _potentially_ something that could work, but #45 is probably a step backwards in that regard. If cross-compilation from WSL to produce Window binaries is a use-case you're looking for can you file an issue with the request?

### cross-compilation is not our use case!

We have to write SW which should work on Linux and Windows.
I tried to analyse the problems we had on our Windows CI build, but on WSL (I like to work on Unix).
And with the restriction to not have the Internet available on CI.

Today I found the Problem and some Workarounds to prevent fetching tools while `cmake configure step`.
We use a `GitHub mirror` and `find_program(NINJA_PATH NAMES ninja.exe ...)` and `find_program(VSWHERE_PATH vswhere.exe ...)` before include the `WindowsToolchain`

**Comment by ClausKlein** [comment]
see too https://github.com/aminya/project_options/issues/165

**Comment by ClausKlein** [comment]
this is substituted by https://github.com/MarkSchofield/WindowsToolchain/pull/49

**Pull request closed without merging**
